@echo off
cd /d C:\Users\nashp\EscoConcepts_Backend
echo Running Git garbage collection...
git gc --auto
echo Adding all changes...
git add .
echo Committing...
git commit -m "Auto update %date% %time%"
echo Pushing to GitHub...
git push
echo Done!
pause